const ALERT = "alert";
const REFETCH_CHAT = "REFETCH_CHAT";
const NEW_ATTACHMENTS = "NEW_ATTACHMENTS";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";
export {
  ALERT,
  REFETCH_CHAT,
  NEW_ATTACHMENTS,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_MESSAGE,
};
